codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: false
    patch:
      default:
        target: auto
        threshold: 0%
        informational: false

comment:
  layout: "reach, diff, files"
  require_changes: true

